//! #32e — embed the design files the app reads at runtime.
//!
//! The phone has no `design/` tree (the APK shipped without it: logcat
//! `connect lower: read setup-01/page.card: No such file or directory`).
//! This script walks the workspace `design/` directory and generates one
//! table (path relative to `design/` -> `&'static [u8]`) that `src/design.rs`
//! serves through `design::file`.
//!
//! The whitelist keeps the APK in budget (the whole tree is 315 MB, mostly
//! review artifacts): text sources the lower pipeline reads — `*.card`,
//! `*.l0`, `*.splash`, the cards' `index.json`, `page.data.json`, the
//! components' runtime json (`index.json`, `kit.json`, `page.data.json`) and
//! the icons the cards name (`*.svg` under `kit/` and `components/`).
//! Everything else — `*.png` (atlas + Stage A/B review renders), `*.log`,
//! `*.md`, evidence/ and review/ directories — stays out.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let design = manifest.join("../../design");
    println!("cargo:rerun-if-changed={}", design.display());

    let mut rows: Vec<(String, PathBuf)> = Vec::new();
    walk(&design, &design, &mut rows);
    // #32g item 1: the kit faces ride in the embed (ux/, ~1.5 MB) — the APK
    // packages only the phone shell's font_assets list, so a
    // crate_resource("self:resources/ux/…") face drew NOTHING on the phone
    // (every card fell back to mono). design::with_fonts points the lowered
    // DSL at the materialized copies.
    let resources = manifest.join("resources");
    println!("cargo:rerun-if-changed={}", resources.display());
    let mut res_rows: Vec<(String, PathBuf)> = Vec::new();
    walk(&resources, &resources, &mut res_rows);
    // Both key shapes: `ux/…`/`icons/…` (design::file / font_file) AND
    // `resources/ux/…`/`resources/icons/…` — the latter is what the
    // script_mod! literals resolve through when ScriptMod::cargo_manifest_path
    // points at the materialized root (design::script_base_dir): `self:` is
    // resolved by makepad against that manifest path (script/res.rs:1067), so
    // the root carrying `resources/` makes EVERY literal work on the phone
    // without text rewriting.
    for (rel, path) in &res_rows {
        rows.push((format!("resources/{rel}"), path.clone()));
    }
    rows.append(&mut res_rows);
    rows.sort();

    let total: usize = rows.iter().map(|(_, p)| p.metadata().map(|m| m.len()).unwrap_or(0) as usize).sum();
    println!("cargo:warning=[octoscode-module] design embed: {} files, {} bytes", rows.len(), total);

    let out = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    let mut g = String::new();
    g.push_str("// @generated by build.rs — the design/ embed table (#32e). Do not edit.\n");
    // An EXPRESSION (an array literal), included at expression position by
    // src/design.rs. Bytes come from include_bytes! of the absolute source
    // path — the generated file stays ~1 line per file, not one literal per
    // byte.
    g.push_str("&[\n");
    for (rel, abs) in &rows {
        let abs = abs.canonicalize().unwrap_or_else(|_| abs.clone());
        g.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            abs.to_string_lossy()
        ));
    }
    g.push_str("]");
    // NO trailing semicolon: the file is included at EXPRESSION position and
    // `incomplete_include` requires a single expression — a `;` makes it a
    // statement (that was the :428 error).
    std::fs::write(out.join("design_embedded.rs"), g).expect("write the embed table");
}

/// The runtime whitelist (see the module doc). `rel` is relative to `design/`.
fn wanted(rel: &str) -> bool {
    let p = Path::new(rel);
    let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
    // Review/capture artifacts never ride in the app.
    for part in p.components() {
        let part = part.as_os_str().to_str().unwrap_or("");
        if matches!(part, "evidence" | "review" | "tools" | "reference") {
            return false;
        }
    }
    if name.starts_with("review-") || name.ends_with(".review.json") {
        return false;
    }
    match p.extension().and_then(|e| e.to_str()).unwrap_or("") {
        "card" | "l0" | "splash" => true,
        "ttf" => rel.starts_with("ux/"),
        // The module's own icons (lib.rs script_mod! names them by
        // self:resources/icons/…); 28K, they ride the embed like the faces.
        "svg" => rel.starts_with("ux/") || rel.starts_with("icons/") || rel.starts_with("cards/") || rel.contains("/kit/") || rel.starts_with("components/"),
        "svg" => rel.starts_with("cards/") || rel.contains("/kit/") || rel.starts_with("components/"),
        "json" => {
            // The per-card trees wholesale: mapped.json (cards.rs structure),
            // semantic-map.json, service-actions.json are runtime reads too,
            // and the whole set is ~3.1 MB — in budget (#32e Do5).
            (rel.starts_with("cards/") || rel.contains("/cards/"))
                || name == "index.json"
                || name == "kit.json"
                || name == "page.data.json"
        }
        _ => false,
    }
}

fn walk(root: &Path, dir: &Path, rows: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, rows);
            continue;
        }
        let Ok(rel) = path.strip_prefix(root) else { continue };
        let rel = rel.to_string_lossy().replace('\\', "/");
        if wanted(&rel) {
            rows.push((rel, path));
        }
    }
}
