//! A24 — the UI language and its Chinese catalog: the web's
//! `features/preferences/ui-text.tsx` (`createUiText`, the lazily loaded
//! `loadChineseCatalog`) and the display preference's `language`
//! (`features/preferences/model.ts`), natively.
//!
//! - **The key is the English source text**, exactly as the web keys it:
//!   [`tr`]`("Settings")` is "设置" in zh and "Settings" in en, and a source
//!   the catalog lacks falls back to the English (`createUiText`,
//!   ui-text.tsx:17-37). [`tr_with`] interpolates `{name}` tokens the way the
//!   web does: a token with no matching param stays as written.
//! - **The catalog is the web's own** ([`zh`], generated by
//!   `tools/i18n/zh_catalog.py` from verbatim copies of `zh.ts`,
//!   `fleet-copy.ts`, `reasoning-copy.ts` and `session-config-copy.ts`),
//!   merged on the first Chinese lookup in the web loader's order — later
//!   tables win ([`catalog`]). An English session never builds it.
//! - **[`alias`]**: native copy that names the SAME control as a web string
//!   with different English (the board's "New chat" is the web's
//!   "New Session") renders that web key's translation. Every entry cites
//!   the web control; a test proves each target is a real web key.
//! - **The language** is the display preference (`screens::a9_prefs`, the
//!   web's `octoscode.web.display.v1`), published here by the launch path and
//!   the Settings control. [`generation`] changes on every switch, so the
//!   host re-renders every surface live ([`tree`] re-texts the static shell,
//!   the lowered surfaces re-lower because their DSL changed).
//! - Never applied to model, user or server prose: only call sites that
//!   carry product copy call [`tr`] (the web's rule, `zh.ts:1`).
pub mod alias;
// A24 phase 2 (+ A31's rows): the reviewed native-only supplement
// (consulted last: web key, then alias, then native).
pub mod native;
pub mod tree;
#[rustfmt::skip]
pub mod zh;

use std::collections::HashMap;
#[cfg(not(test))]
use std::sync::atomic::AtomicU8;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::OnceLock;

/// `UiLanguage` (model.ts:10): the two interface languages.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Lang {
    En,
    Zh,
}

impl Lang {
    /// The stored code (`"en"` / `"zh"`).
    pub fn code(self) -> &'static str {
        match self {
            Lang::En => "en",
            Lang::Zh => "zh",
        }
    }

    /// `isUiLanguage` (model.ts:30-32): exactly `"en"` or `"zh"`.
    pub fn parse(value: &str) -> Option<Lang> {
        match value {
            "en" => Some(Lang::En),
            "zh" => Some(Lang::Zh),
            _ => None,
        }
    }

    /// The device default (model.ts:102-104): a locale matching
    /// `/^zh(?:-|_|$)/i` is Chinese, anything else English.
    pub fn for_locale(tag: &str) -> Lang {
        let t = tag.trim();
        let zh = t.len() >= 2
            && t[..2].eq_ignore_ascii_case("zh")
            && matches!(t.as_bytes().get(2), None | Some(b'-') | Some(b'_'));
        if zh {
            Lang::Zh
        } else {
            Lang::En
        }
    }
}

#[cfg(not(test))]
static LANG_ZH: AtomicU8 = AtomicU8::new(0);
// Unit tests run in parallel threads: a test that switches to Chinese must
// not leak into another test's English assertions, so under `cfg(test)` the
// language is per thread (production keeps one process-wide value).
#[cfg(test)]
thread_local! {
    static LANG_ZH: std::cell::Cell<u8> = const { std::cell::Cell::new(0) };
}
static GENERATION: AtomicU64 = AtomicU64::new(0);
static CATALOG_LOADED: AtomicBool = AtomicBool::new(false);

fn load_lang() -> u8 {
    #[cfg(not(test))]
    {
        LANG_ZH.load(Ordering::Acquire)
    }
    #[cfg(test)]
    {
        LANG_ZH.with(|c| c.get())
    }
}

fn swap_lang(v: u8) -> u8 {
    #[cfg(not(test))]
    {
        LANG_ZH.swap(v, Ordering::AcqRel)
    }
    #[cfg(test)]
    {
        LANG_ZH.with(|c| c.replace(v))
    }
}

/// The interface language in effect.
pub fn language() -> Lang {
    if load_lang() == 1 {
        Lang::Zh
    } else {
        Lang::En
    }
}

pub fn is_zh() -> bool {
    language() == Lang::Zh
}

/// Switch the interface language. Returns whether it changed; a change
/// bumps [`generation`] so every surface re-renders in the new language.
pub fn set_language(lang: Lang) -> bool {
    let v = u8::from(lang == Lang::Zh);
    if swap_lang(v) == v {
        return false;
    }
    GENERATION.fetch_add(1, Ordering::AcqRel);
    true
}

/// Bumped on every language switch: a cache keyed by it (a lowered row,
/// the static shell's texts) knows it is stale.
pub fn generation() -> u64 {
    GENERATION.load(Ordering::Acquire)
}

/// The loaded Chinese catalog: the web's tables merged in the web's order
/// (`loadChineseCatalog`, ui-text.tsx:42-67 — a later table wins), built on
/// the first Chinese lookup.
pub fn catalog() -> &'static HashMap<&'static str, &'static str> {
    static CATALOG: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    CATALOG.get_or_init(|| {
        let mut map = HashMap::with_capacity(zh::MERGED_LEN);
        for table in zh::TABLES {
            for (source, translated) in table.iter() {
                map.insert(*source, *translated);
            }
        }
        CATALOG_LOADED.store(true, Ordering::Release);
        map
    })
}

/// Whether the Chinese catalog has been built (an English session never
/// needs it).
pub fn catalog_loaded() -> bool {
    CATALOG_LOADED.load(Ordering::Acquire)
}

/// The Chinese text for an English source: the web key itself, else the
/// web key of the same control ([`alias`]), else native copy the web has
/// no screen for ([`native`], board 4), each also tried with
/// typographic quotes made straight (the native copy writes `can’t` where
/// the web's key has `can't` — one string, two spellings); `None` = no web
/// translation.
pub fn zh_for(source: &str) -> Option<&'static str> {
    web_zh(source).or_else(|| native_zh(source))
}

/// The web's own Chinese for a source: its catalog key, or the web key of
/// the same control ([`alias`]), with typographic quotes folded.
pub fn web_zh(source: &str) -> Option<&'static str> {
    let cat = catalog();
    let lookup = |s: &str| {
        cat.get(s)
            .copied()
            .or_else(|| alias::web_key(s).and_then(|k| cat.get(k).copied()))
            // A30: the web's peer table (`peer-copy.ts`), which the web's
            // loader never merges — after the merged catalog, so a merged
            // key always wins.
            .or_else(|| zh::PEER_ZH.iter().find(|(k, _)| *k == s).map(|(_, v)| *v))
    };
    lookup(source).or_else(|| fold_quotes(source).and_then(|plain| lookup(&plain)))
}

/// The reviewed native-only supplement ([`native`]), consulted after the
/// web: copy the web has no Chinese for.
pub fn native_zh(source: &str) -> Option<&'static str> {
    static NATIVE: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    let map = NATIVE.get_or_init(|| native::NATIVE_ZH.iter().copied().collect());
    map.get(source).copied().or_else(|| fold_quotes(source).and_then(|plain| map.get(plain.as_str()).copied()))
}

/// `can’t` -> `can't`, `“x”` -> `"x"` (None when there is nothing to fold).
fn fold_quotes(source: &str) -> Option<String> {
    source
        .contains(['\u{2018}', '\u{2019}', '\u{201c}', '\u{201d}'])
        .then(|| source.replace(['\u{2018}', '\u{2019}'], "'").replace(['\u{201c}', '\u{201d}'], "\""))
}

/// `t(source)` in `lang` (no interpolation).
pub fn tr_in(lang: Lang, source: &str) -> &str {
    match lang {
        Lang::Zh => zh_for(source).unwrap_or(source),
        Lang::En => source,
    }
}

/// `t(source)` in the current language: the web's Chinese for a web key,
/// the English source otherwise. Never allocates.
pub fn tr(source: &str) -> &str {
    tr_in(language(), source)
}

/// One English word, two meanings: the theme's "System" reads 跟随系统, a
/// system notice's "System" reads 系统. A native entry keyed
/// `"<ctx>|<source>"` wins in that context; otherwise plain [`tr`]. The
/// English is the source either way (no renamed copy).
pub fn tr_ctx<'a>(ctx: &str, source: &'a str) -> &'a str {
    if is_zh() {
        if let Some(zh) = native_zh(&format!("{ctx}|{source}")) {
            return zh;
        }
    }
    tr(source)
}

/// `createUiText(lang, catalog)(source, params)` (ui-text.tsx:17-37):
/// translate, then replace each `{name}` token whose name is a param; a
/// token with no param stays as written.
pub fn text_in(lang: Lang, source: &str, params: &[(&str, &str)]) -> String {
    interpolate(tr_in(lang, source), params)
}

/// `t(source, params)` in the current language.
pub fn tr_with(source: &str, params: &[(&str, &str)]) -> String {
    text_in(language(), source, params)
}

/// Copy shown in English ON PURPOSE in every language: one control must
/// read in one language, and a native-only control whose siblings have no
/// web key (Settings > Model's "Off | On | High") stays English rather than
/// mixing "Off | On | 高". The source scan accepts it as a decision, not a
/// bypass; a web key for every sibling turns it into `tr()`.
pub fn keep(source: &str) -> &str {
    source
}

/// `t(source, {value0})` — the web's generated keys name their one
/// placeholder `{value0}`.
pub fn tr1(source: &str, value0: &str) -> String {
    tr_with(source, &[("value0", value0)])
}

/// [`tr1`] through a context entry ([`tr_ctx`]): a duration's "{value0}m"
/// (18 分钟) is not the sidebar's "{value0}m" ago (18 分钟前).
pub fn tr1_ctx(ctx: &str, source: &str, value0: &str) -> String {
    interpolate(tr_ctx(ctx, source), &[("value0", value0)])
}

/// The web's `/\{([^{}]+)\}/g` replacement (ui-text.tsx:29-35).
pub fn interpolate(text: &str, params: &[(&str, &str)]) -> String {
    if params.is_empty() {
        return text.to_owned();
    }
    let mut out = String::with_capacity(text.len() + 16);
    let mut rest = text;
    while let Some(open) = rest.find('{') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        match after.find(['{', '}']) {
            Some(close) if after.as_bytes()[close] == b'}' && close > 0 => {
                let name = &after[..close];
                match params.iter().find(|(k, _)| *k == name) {
                    Some((_, v)) => out.push_str(v),
                    None => {
                        out.push('{');
                        out.push_str(name);
                        out.push('}');
                    }
                }
                rest = &after[close + 1..];
            }
            _ => {
                out.push('{');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

/// The device's locale tag: on macOS the first preferred language
/// (`CFLocaleCopyPreferredLanguages`, what `navigator.language` reports in a
/// browser there), else the POSIX environment (`LC_ALL`, `LC_MESSAGES`,
/// `LANG`; `C`/`POSIX` say nothing).
pub fn device_locale() -> String {
    #[cfg(target_os = "macos")]
    if let Some(tag) = macos::preferred_language() {
        return tag;
    }
    for var in ["LC_ALL", "LC_MESSAGES", "LANG"] {
        if let Ok(v) = std::env::var(var) {
            let v = v.trim();
            if !v.is_empty() && v != "C" && v != "POSIX" {
                return v.to_owned();
            }
        }
    }
    String::new()
}

/// The default language of a fresh profile (model.ts:102-104).
pub fn device_language() -> Lang {
    Lang::for_locale(&device_locale())
}

#[cfg(target_os = "macos")]
mod macos {
    use std::ffi::{c_char, c_void, CStr};

    type CFTypeRef = *const c_void;
    type CFIndex = isize;
    const UTF8: u32 = 0x0800_0100;

    #[link(name = "CoreFoundation", kind = "framework")]
    extern "C" {
        fn CFLocaleCopyPreferredLanguages() -> CFTypeRef;
        fn CFArrayGetCount(array: CFTypeRef) -> CFIndex;
        fn CFArrayGetValueAtIndex(array: CFTypeRef, index: CFIndex) -> CFTypeRef;
        fn CFStringGetCString(s: CFTypeRef, buffer: *mut c_char, size: CFIndex, encoding: u32) -> u8;
        fn CFRelease(cf: CFTypeRef);
    }

    /// The first of the user's preferred languages (`zh-Hans-CN`, `en-US`).
    pub fn preferred_language() -> Option<String> {
        // SAFETY: CFLocaleCopyPreferredLanguages returns an owned (+1) CFArray
        // of CFStrings or null; the element is borrowed from the array while
        // it lives, CFStringGetCString writes at most `size` bytes into our
        // buffer (NUL-terminated on success), and the array is released once.
        unsafe {
            let array = CFLocaleCopyPreferredLanguages();
            if array.is_null() {
                return None;
            }
            let mut out = None;
            if CFArrayGetCount(array) > 0 {
                let first = CFArrayGetValueAtIndex(array, 0);
                let mut buf = [0 as c_char; 64];
                if !first.is_null() && CFStringGetCString(first, buf.as_mut_ptr(), buf.len() as CFIndex, UTF8) != 0 {
                    out = Some(CStr::from_ptr(buf.as_ptr()).to_string_lossy().into_owned());
                }
            }
            CFRelease(array);
            out.filter(|s| !s.is_empty())
        }
    }
}

#[cfg(test)]
mod tests;
